version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"